### ISSUE TITLE
why not give the website map file?

### ISSUE THREAD

**Issue by Metatron001** [meixiangdao/Hello#1]
as same as the title, your project need it.

**Comment by meixiangdao** [comment]
# ok, I will fix it.

**Comment by meixiangdao** [comment]
### ok, I'll fix it soon.

**Comment by Metatron001** [comment]
close?

**Comment by meixiangdao** [comment]
yes, I have understood the issue column~~

**Comment by Metatron001** [comment]
eh, how can I reply you by referring your word?
